#!/usr/bin/env python

import os, sys
from twisted.internet import reactor
from polarrose.amazon.sqs import SimpleQueueService

if __name__ == "__main__":

    def printResult(response):
        for queue in response.queues:
            print queue.url
        reactor.stop()

    def printError(failure):
        print "failure: " + str(failure)
        reactor.stop()

    service = SimpleQueueService(key = os.environ.get("AWS_KEY"), secret = os.environ.get("AWS_SECRET"))
    service.listQueues().addCallback(printResult).addErrback(printError)
    reactor.run()
    
